# Generated by Django 3.1.3 on 2020-12-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=280, upload_to='images/% Y/% m/% d/', width_field=336)),
                ('user_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geostats.userentity')),
            ],
        ),
    ]
