# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-11-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geostats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_of', to='geostats.Town'),
        ),
    ]
