# Generated by Django 3.1.3 on 2020-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostats', '0002_userentityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentityimage',
            name='image',
            field=models.ImageField(height_field=280, upload_to='images/%Y/', width_field=336),
        ),
    ]
