# Generated by Django 3.1.3 on 2020-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geostats', '0003_auto_20201208_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentityimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/'),
        ),
    ]
