# Generated by Django 3.1.3 on 2020-11-17 17:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('geostats', '0006_auto_20201116_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userentity',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
